### ISSUE TITLE
review

### ISSUE THREAD

**Issue by thautwarm** [GiggleLiu/nilangpaper#3]
stmts in the right hand side should be stmts1, stmts2.

https://github.com/GiggleLiu/nilangpaper/blob/0122e58b45ba8d568d0a8cc13939351b8a1051d4/invc.tex#L279

**Comment by thautwarm** [comment]
typo, shall be single param
https://github.com/GiggleLiu/nilangpaper/blob/0122e58b45ba8d568d0a8cc13939351b8a1051d4/invc.tex#L399

**Comment by thautwarm** [comment]
之前旧的typo也都没改。

**Comment by thautwarm** [comment]
https://github.com/GiggleLiu/nilangpaper/blob/0122e58b45ba8d568d0a8cc13939351b8a1051d4/invc.tex#L344

after `#after stage 2`, we'd better add more explanations. `..., we got the reversed IR`

**Comment by thautwarm** [comment]
I checked the "Language Design" chapter twice, and assured the language proposal is clear, the statements make sense.

**Comment by thautwarm** [comment]
The blank left in the LHS of Appendix A looks not that good to me.

**Comment by thautwarm** [comment]
new typos in Appendix A found. attention.

**Comment by thautwarm** [comment]
bnf change:
https://github.com/GiggleLiu/nilangpaper/blob/309d89c556689c8331596f81ba9f1171bca08901/bnf#L64

As multi-param is supported, it shall be

` <$JuliaExpr$> '(' [DataViews] ')'` instead of ` <$JuliaExpr$> '(' DataView ')'`.

For keyword arguments:
```julia
KwArg : <ident> '=' <$JuliaExpr$>;
KwArgs : [KwArgs ','] KwArg ;

DataView : DataView '[' <$JuliaExpr$> ']'
         ...
         | <$JuliaExpr$> '(' [DataViews] [';' KwArgs] ')'
         ...
```
Then regenerate the tex

**Comment by GiggleLiu** [comment]
Thanks for the comments. I have changed according to your suggestions. One thing to correct

> As multi-param is supported

This is not true, here the `dataview` function takes exactly one parameter.
