### ISSUE TITLE
polish

### ISSUE THREAD

**Issue by thautwarm** [GiggleLiu/nilangpaper#4]
some typos:
1. "traning" is wrong, in https://github.com/GiggleLiu/nilangpaper/blob/436802be9b069e3bd86b14923a821435e90a1643/invc.tex#L237

2. "reversive" should be "recursive", in https://github.com/GiggleLiu/nilangpaper/blob/436802be9b069e3bd86b14923a821435e90a1643/invc.tex#L658

non-typo stuffs:

3. use qualified notations for `MacroTools.prettify`:
   https://github.com/GiggleLiu/nilangpaper/blob/436802be9b069e3bd86b14923a821435e90a1643/invc.tex#L281

    `using MacroTools: prettify`, that is because readers not from Julia cannot immediately understand where the function is from.

4. `#$ TODO: remove this comment` https://github.com/GiggleLiu/nilangpaper/blob/436802be9b069e3bd86b14923a821435e90a1643/invc.tex#L295

5. a lot to change as you use new notations as alternatives of `@anc` and `@deanc`.

**Comment by GiggleLiu** [comment]
About 4, this is a dirty fix for latex highlight in `vim`. I will remove it when the paper is ready.
